name: README Chess

on:
  issues:
    types: [opened]
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  handle-chess:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.issue.title, 'Chess:') || startsWith(github.event.issue.title, 'chess:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-chess

      - name: Run chess updater
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python scripts/readme_chess.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "♟️ Update README chess board"
          file_pattern: |
            README.md
            games/*.pgn

      - name: Close triggering issue (if any)
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              state: 'closed'
            });